apiVersion: v1
kind: Service
metadata:
  name: chichat
  labels:
    app: chichat
spec:
  selector:
    app: chichat
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
