apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: chichat-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: chichat
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - default  # or your app namespace
